{% set version = "2.7.1" %}
{% set version_list = version.split('.') %}
{% set tarversion = version_list[0]+version_list[1]+'r'+version_list[2] %}
{% set name = "nauty" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://pallini.di.uniroma1.it/nauty{{ tarversion }}.tar.gz
  sha256: 76ca5d196e402c83a987f90c28ff706bcc5a333bb4a8fbb979a62d3b99c34e77

build:
  number: 1
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - make                  # [unix]
    - clangdev              # [win]
    - llvmdev               # [win]
    - lld                   # [win]
    - m2-make               # [win]
    - m2-automake-wrapper   # [win]
    - m2-libtool            # [win]
    - m2-autoconf           # [win]
    - posix                 # [win]

test:
  commands:
    - addedgeg -help
    - test -f $PREFIX/include/nauty/nauty.h                 # [unix]
    - if not exist %LIBRARY_INC%/nauty/nauty.h exit 1       # [win]
    - test -f $PREFIX/include/nauty/traces.h                # [unix]
    - if not exist %LIBRARY_INC%/nauty/traces.h exit 1      # [win]
    - test -f $PREFIX/include/nauty/nausparse.h             # [unix]
    - if not exist %LIBRARY_INC%/nauty/nausparse.h exit 1   # [win]
    - test -f $PREFIX/lib/libnauty.a                        # [unix]
    - if not exist %LIBRARY_LIB%/nauty.lib exit 1           # [win]

about:
  home: http://users.cecs.anu.edu.au/~bdm/nauty/
  license: Apache-2.0
  license_file: COPYRIGHT
  summary: nauty and Traces are programs for computing automorphism groups of graphs and digraphs.

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
